[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["Game2048Env"]

[project]
name = "Game2048Env"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "numpy",
  "pre-commit",
]
